import Vue from 'vue'
import {
  Button,
  Form,
  FormItem,
  Input,
  Message,
  Container,
  Aside,
  Main,
  Header,
  Card,
  Avatar,
  Menu,
  MenuItemGroup,
  MenuItem,
  Submenu,
  Row,
  Col,
  Breadcrumb,
  BreadcrumbItem,
  Table,
  TableColumn,
  Tag,
  Pagination,
  Select,
  Option,
  Dialog,
  Upload,
  DatePicker,
  MessageBox,
  Loading,
  Radio,
  Image,
  Checkbox,
  Divider,
  Popover
} from 'element-ui'

Vue.use(Button)
Vue.use(Form)
Vue.use(FormItem)
Vue.use(Input)
Vue.use(Container)
Vue.use(Aside)
Vue.use(Main)
Vue.use(Header)
Vue.use(Card)
Vue.use(Avatar)
Vue.use(MenuItemGroup)
Vue.use(MenuItem)
Vue.use(Menu)
Vue.use(Submenu)
Vue.use(Row)
Vue.use(Col)
Vue.use(Breadcrumb)
Vue.use(BreadcrumbItem)
Vue.use(Table)
Vue.use(TableColumn)
Vue.use(Tag)
Vue.use(Pagination)
Vue.use(Select)
Vue.use(Option)
Vue.use(Dialog)
Vue.use(Upload)
Vue.use(DatePicker)
Vue.use(Loading)
Vue.use(Radio)
Vue.use(Image)
Vue.use(Checkbox)
Vue.use(Divider)
Vue.use(Popover)
Vue.prototype.$message = Message
Vue.prototype.$confirm = MessageBox.confirm
